micronaut:
  application:
    name: keymanager

grpc:
  server:
    port: ${GRPC_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_HOST:`jdbc:postgresql://localhost:5432/keymanager`}
    username: ${DB_USER:root}
    password: ${DB_PASS:Root@12345}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

jackson.serialization.writeDatesAsTimestamps: false

itau:
  contas:
    url: ${ITAU_CLIENT_URL:`http://localhost:9091`}

bcb:
  pix:
    url: ${BCB_CLIENT_URL:`http://localhost:8082`}
