apiVersion: v1
kind: Secret
metadata:
  name: orange-talents-05-template-pix-keymanager-grpc-secrets
type: Opaque
data:
  DB_USER: {{ .Values.application.DB_USER | b64enc | quote  }}
  DB_PASS: {{ .Values.application.DB_PASS | b64enc | quote  }}